<a href="https://colab.research.google.com/github/wisamabdullah85/Machine-Learning-BitCoin/blob/main/Applied_LR%2CSVM%2CMLP%2CRF%2CKNDTGNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
# استيراد المكتبات اللازمة
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline

In [40]:
# تحميل الداتا سيت المحسن
data = pd.read_csv('/content/updated_dataset.csv')

In [41]:
data.columns

Index(['Last Price', 'Open Price', 'Max', 'Min', 'Size', 'Change Persent',
       'Class'],
      dtype='object')

In [42]:
# تحديد المتغيرات المستقلة والمتغير الهدف
X = data.drop('Class', axis=1)  # استبدل 'Target_Column' بالعمود الهدف في بياناتك
y = data['Class']

In [43]:
# تقسيم البيانات إلى مجموعة تدريب ومجموعة اختبار
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [44]:
# تطبيع البيانات
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [45]:
# تهيئة محسن لملء القيم المفقودة بالمتوسط
imputer = SimpleImputer(strategy='mean')

In [46]:
# تحديث الكود لاستخدام النماذج مع محسن في Pipeline
models = {
    "Logistic Regression": make_pipeline(imputer, LogisticRegression()),
    "SVM": make_pipeline(imputer, SVC()),
    "Decision Tree": make_pipeline(imputer, DecisionTreeClassifier()),
    "Random Forest": make_pipeline(imputer, RandomForestClassifier()),
    "KNN": make_pipeline(imputer, KNeighborsClassifier()),
    "Gaussian NB": make_pipeline(imputer, GaussianNB()),
    "Perceptron": make_pipeline(imputer, Perceptron()),
    "Gradient Boosting": make_pipeline(imputer, GradientBoostingClassifier())
}

In [47]:
# data[''].fillna(0, inplace = True)
#data['Size'].fillna(0, inplace = True)

In [48]:
print(data.isnull().sum())

Last Price        0
Open Price        0
Max               0
Min               0
Size              2
Change Persent    0
Class             0
dtype: int64


In [49]:
# تطبيق الخوارزميات وتقييمها
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(f"{name} Performance:")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Classification Report:")
    print(classification_report(y_test, y_pred))
    print("-----------------------------------")

Logistic Regression Performance:
Confusion Matrix:
[[36  0  1  2  0  0  1  0  0  0  0  3  0]
 [ 0 39  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  7  1  8  1  0  0  7  0  0]
 [15  0  0 29  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  0 21  0 11  1  0  0  2  0  0]
 [ 1  0  0  0  0  5  0  9  0  0 21  7  0]
 [ 1  0  7  0  0  0  3  6  0  0 20  0  0]
 [ 1  0  0  0  0  0  0  0  0  0 37  3  0]
 [39  0  0  8  0  0  0  0  0  0  0  3  0]
 [ 1  0  0  0  0  0  0  0  0  0 21 21  0]
 [ 0  0  0  0  0  0  0 13  0  0 24  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 22 15  0]
 [ 0  0  5  0  0  0  5 10  0  0 24  0  0]]
Accuracy: 0.35036496350364965
Classification Report:
                   precision    recall  f1-score   support

     Binance Coin       0.38      0.84      0.53        43
          Bitcoin       1.00      1.00      1.00        39
    Bitcoin Cash        0.45      0.45      0.45        44
        Dogecoin        0.74      0.66      0.70        44
         Ethereum       0.75      0.46      0.57     

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM Performance:
Confusion Matrix:
[[23  0  0  5  0  0  0  0  0  0  0 15  0]
 [ 0 39  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  5  0  0  0  9 26  0]
 [14  0  0 29  0  0  0  0  0  0  0  1  0]
 [ 0  0  6  0 14  2  4  0  0  0  2 18  0]
 [ 0  0  0  0  0  3  5  0  0  0  6 29  0]
 [ 0  0  0  0  0  3  4  0  0  0  4 26  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 41  0]
 [30  0  0 12  0  0  0  0  0  0  1  7  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 43  0]
 [ 0  0  0  0  0  3  8  0  0  0  4 22  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 37  0]
 [ 0  0  1  0  0  4  7  0  0  0  8 24  0]]
Accuracy: 0.2791970802919708
Classification Report:
                   precision    recall  f1-score   support

     Binance Coin       0.34      0.53      0.42        43
          Bitcoin       1.00      1.00      1.00        39
    Bitcoin Cash        0.00      0.00      0.00        44
        Dogecoin        0.63      0.66      0.64        44
         Ethereum       1.00      0.30      0.47        46
Ethereum Cl

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Random Forest Performance:
Confusion Matrix:
[[ 7  0  0  0  0  0  0  0 36  0  0  0  0]
 [ 0 39  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 38  0  2  0  1  0  0  0  0  0  3]
 [ 0  0  0 43  0  0  0  0  1  0  0  0  0]
 [ 0  0  2  0 38  0  5  0  0  0  0  0  1]
 [ 0  0  0  0  0 40  2  0  0  0  1  0  0]
 [ 0  0  0  0  0  1 28  0  0  0  0  0  8]
 [ 0  0  0  0  0  0  0 34  0  5  0  2  0]
 [46  0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0 30  0  6  0]
 [ 0  0  0  0  0  4  0  0  0  0 33  0  0]
 [ 0  0  0  0  0  0  0  6  0  7  0 24  0]
 [ 0  0  2  0  0  0  7  0  0  0  0  0 35]]
Accuracy: 0.7171532846715328
Classification Report:
                   precision    recall  f1-score   support

     Binance Coin       0.13      0.16      0.15        43
          Bitcoin       1.00      1.00      1.00        39
    Bitcoin Cash        0.90      0.86      0.88        44
        Dogecoin        1.00      0.98      0.99        44
         Ethereum       0.95      0.83      0.88        46
E

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classif

Gradient Boosting Performance:
Confusion Matrix:
[[ 5  0  1  0  0  0  0  0 37  0  0  0  0]
 [ 0 39  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 38  0  3  0  0  0  0  0  0  0  3]
 [ 0  0  0 43  0  0  0  0  1  0  0  0  0]
 [ 0  0  4  0 37  0  5  0  0  0  0  0  0]
 [ 0  0  0  0  0 38  3  0  0  0  1  0  1]
 [ 0  0  0  0  0  2 26  0  0  0  0  0  9]
 [ 0  0  0  0  0  0  0 28  0  8  0  5  0]
 [45  0  0  0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  0  6  0 28  0  9  0]
 [ 0  0  0  0  0  3  0  0  0  0 34  0  0]
 [ 0  0  0  0  0  0  0  5  0 12  0 20  0]
 [ 0  0  2  0  0  0  8  0  0  0  0  0 34]]
Accuracy: 0.6843065693430657
Classification Report:
                   precision    recall  f1-score   support

     Binance Coin       0.10      0.12      0.11        43
          Bitcoin       1.00      1.00      1.00        39
    Bitcoin Cash        0.84      0.86      0.85        44
        Dogecoin        1.00      0.98      0.99        44
         Ethereum       0.93      0.80      0.86        