<a href="https://colab.research.google.com/github/wisamabdullah85/Machine-Learning-BitCoin/blob/main/tensorflowwithOneHotEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [35]:
# قراءة الداتا سيت
data = pd.read_csv('/content/processed_dataset.csv')

In [36]:
# تطبيق One-Hot Encoding على عمود 'Class'
encoder = OneHotEncoder()
class_encoded = encoder.fit_transform(data[['Class']]).toarray()
class_encoded_df = pd.DataFrame(class_encoded, columns=encoder.get_feature_names_out(['Class']))

In [37]:
# إزالة عمود 'Class' وإضافة الأعمدة المُشفرة
data_without_class = data.drop('Class', axis=1)
data_prepared = pd.concat([data_without_class, class_encoded_df], axis=1)


In [38]:
# تقسيم الداتا سيت إلى مجموعات التدريب والاختبار
X = data_prepared.iloc[:, :-len(class_encoded_df.columns)] # الميزات
y = data_prepared.iloc[:, -len(class_encoded_df.columns):] # الأهداف
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [39]:
# بناء نموذج التعلم العميق
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(y_train.shape[1], activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


In [40]:
# تدريب النموذج
model.fit(X_train, y_train, epochs=100, batch_size=64)

Epoch 1/100
35/35 [==============================] - 1s 2ms/step - loss: 2.4708 - accuracy: 0.1839
Epoch 2/100
35/35 [==============================] - 0s 2ms/step - loss: 2.2520 - accuracy: 0.2112
Epoch 3/100
35/35 [==============================] - 0s 2ms/step - loss: 2.0685 - accuracy: 0.2559
Epoch 4/100
35/35 [==============================] - 0s 2ms/step - loss: 1.9342 - accuracy: 0.2933
Epoch 5/100
35/35 [==============================] - 0s 2ms/step - loss: 1.8304 - accuracy: 0.3166
Epoch 6/100
35/35 [==============================] - 0s 2ms/step - loss: 1.7371 - accuracy: 0.3380
Epoch 7/100
35/35 [==============================] - 0s 2ms/step - loss: 1.6612 - accuracy: 0.3609
Epoch 8/100
35/35 [==============================] - 0s 2ms/step - loss: 1.6026 - accuracy: 0.3659
Epoch 9/100
35/35 [==============================] - 0s 2ms/step - loss: 1.5576 - accuracy: 0.3846
Epoch 10/100
35/35 [==============================] - 0s 2ms/step - loss: 1.5206 - accuracy: 0.3791
Epoch 11/

In [41]:
# تقييم النموذج
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Loss: {loss}, Accuracy: {accuracy}')

18/18 [==============================] - 0s 2ms/step - loss: 1.0236 - accuracy: 0.5602
Loss: 1.0235778093338013, Accuracy: 0.5602189898490906


In [42]:
# التنبؤ بالبيانات الاختبارية
y_pred = model.predict(X_test)
y_pred_labels = np.argmax(y_pred, axis=1)
y_test_labels = np.argmax(y_test.to_numpy(), axis=1)

18/18 [==============================] - 0s 2ms/step


In [43]:
# حساب مصفوفة الالتباس
conf_matrix = confusion_matrix(y_test_labels, y_pred_labels)
print('Confusion Matrix:\n', conf_matrix)

Confusion Matrix:
 [[ 3  0  2  3  0  0  0  4 31  0  0  0  0]
 [ 0 30  0  0  9  0  0  0  0  0  0  0  0]
 [ 0  6 21  0 12  0  1  0  0  0  0  0  4]
 [ 0  0  0 28  0  0  0  2 13  1  0  0  0]
 [ 0  8  1  0 31  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0 35  2  1  0  0  2  0  3]
 [ 0  0  6  0  0  2 17  0  0  0  0  0 12]
 [ 0  0  0  0  0  0  0 29  3  7  0  2  0]
 [ 5  0  0 13  0  0  0  2 30  0  0  0  0]
 [ 0  0  0  0  0  0  0  9  5 11  0 18  0]
 [ 6  0  0  3  0  2  0  2  1  1 20  2  0]
 [ 0  0  0  2  0  0  0  9  5  4  0 17  0]
 [ 0  0  4  0  0  2  3  0  0  0  0  0 35]]
